name: 'Node Setup'
description: 'Basically, just setup Node.js'
runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.19.0